# Classifying Iris Flower Species With K-Nearest Neighbours From Scratch

## Introduction

In this project, I am going to write a programme with k-nearest neighbours algorithm (k-NN) in R to classify Iris flower species.

The Iris dataset has already been built into R. This dataset includes 150 observations with 5 features of Iris flower.

I'll start by setting up the workplace, importing the required packages and loading the dataset.

In [1]:
# Clean working environment
rm(list=ls())

# Import packages
library(repr)
library(gridExtra)
library(ggplot2)
library(GGally)
library(gmodels)

# Load dataset
data(iris)

## Data Exploration

In this section, I'll explore the Iris dataset by measuring some commonly used quantities in descriptive statistics and visualizing those important features in Iris dataset.

First I'll use `str` and `head` function to preview the data frame. It provides some basic informations about the Iris flower dataset.

In [2]:
# Show dataset structure
str(iris)

# Show first few row
head(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

The Iris dataset contains 150 observations, 4 numerical variables and 1 categorical variable.

### Exploring Numerical Variables

Now I'll explore the numerical variables in Iris dataset by measuring their central tendency and dispersion. Also I'll visualize some characteristic of those numerical variables.

In [3]:
# Measure central tendency and dispersion of Iris dataset
summary(iris[,-5])

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  

In [4]:
# Visualise distribution of data by boxplot
options(repr.plot.width=11, repr.plot.height=7.33)
box1 <- ggplot(iris, aes(x=Species, y=Sepal.Length, fill=Species)) + geom_boxplot(width=0.5) + coord_flip() + 
    theme(axis.line=element_line(color="black"), legend.position=c(0.875,0.2)) + xlab("Species") + ylab("Sepal Length")
box2 <- ggplot(iris, aes(x=Species, y=Sepal.Width, fill=Species)) + geom_boxplot(width=0.5) + coord_flip() + 
    theme(axis.line=element_line(color="black"), legend.position=c(0.88,0.8)) + xlab("Species") + ylab("Sepal Width")
box3 <- ggplot(iris, aes(x=Species, y=Petal.Length, fill=Species)) + geom_boxplot(width=0.5) + coord_flip() + 
    theme(axis.line=element_line(color="black"), legend.position=c(0.875,0.2)) + xlab("Species") + ylab("Petal Length")
box4 <- ggplot(iris, aes(x=Species, y=Petal.Width, fill=Species)) + geom_boxplot(width=0.5) + coord_flip() + 
    theme(axis.line=element_line(color="black"), legend.position=c(0.875,0.2)) + xlab("Species") + ylab("Petal Width")
grid.arrange(box1, box2, box3, box4, nrow=2, ncol=2)

In [5]:
# Visualise frequency distribution by histogram
options(repr.plot.width=11, repr.plot.height=7.33)
hist1 <- ggplot(iris, aes(x=Sepal.Length, fill=Species)) + geom_histogram(bins=25) + 
    theme(axis.line=element_line(color="black"), legend.position=c(0.875,0.8)) + xlab("Sepal Length") + ylab("Frequency")
hist2 <- ggplot(iris, aes(x=Sepal.Width, fill=Species)) + geom_histogram(bins=25) + 
    theme(axis.line=element_line(color="black"), legend.position=c(0.875,0.8)) + xlab("Sepal Width") + ylab("Frequency")
hist3 <- ggplot(iris, aes(x=Petal.Length, fill=Species)) + geom_histogram(bins=25) + 
    theme(axis.line=element_line(color="black"), legend.position=c(0.875,0.8)) + xlab("Petal Length") + ylab("Frequency")
hist4 <- ggplot(iris, aes(x=Petal.Width, fill=Species)) + geom_histogram(bins=25) + 
    theme(axis.line=element_line(color="black"), legend.position=c(0.875,0.8)) + xlab("Petal Width") + ylab("Frequency")
grid.arrange(hist1, hist2, hist3, hist4, nrow=2, ncol=2)

### Exploring Categorical Variables

Apart from the numerical variable, the Iris dataset also contains a categorical features, 'Species'. I'll explore the categorical variable by looking at the number of observation of each category.

In [6]:
# Show all Iris species
unique(iris$Species)

# Show Iris species ratio
round(table(iris$Species)/length(iris$Species),3)

# Visualise the result
options(repr.plot.width=3, repr.plot.height=4.5)
ggplot(iris, aes(x=Species)) + geom_bar(width=0.5, fill="seagreen1") + theme(axis.line=element_line(color="black")) + xlab("Iris Species") + ylab("No. of observation")

[1] setosa     versicolor virginica 
Levels: setosa versicolor virginica


    setosa versicolor  virginica 
     0.333      0.333      0.333 

The variable 'Species' contains three categories, i.e., setosa, versicolor and virginica, and each category contains the same amount of observations.

### Exploring Relationships Between Variables

In [7]:
# Compute simple correlation
(cor_iris <- round(cor(iris[,-5]),3))

# Visualise the association by scatter plot
options(repr.plot.width=9.5, repr.plot.height=6.33)
ggpairs(iris, columns=c("Sepal.Length","Sepal.Width","Petal.Length","Petal.Width"), aes(color=Species))

Sepal.Length Sepal.Width Petal.Length Petal.Width
Sepal.Length  1.000       -0.118       0.872        0.818     
Sepal.Width  -0.118        1.000      -0.428       -0.366     
Petal.Length  0.872       -0.428       1.000        0.963     
Petal.Width   0.818       -0.366       0.963        1.000

The correlation coeifficient between sepal length and sepal width is -0.118, and it is beyond my expectation. Hence, I will further explore the association between sepal length and sepal width by controlling the effects of petal length and petal width. To study more about partial corrleation, visit https://en.wikipedia.org/wiki/Partial_correlation.

In [8]:
# Compute partial correlation between sepal length and width by controlling R.V. petal length and width
cov_iris <- cov(iris[,-5])
prtl_S <- cov_iris[1:2,1:2] - cov_iris[1:2,3:4] %*% solve(cov_iris[3:4,3:4]) %*% cov_iris[3:4,1:2]
prtl_cor <- prtl_S[1,2]/sqrt(prtl_S[1,1] * prtl_S[2,2])
sprintf("The partial correlation is %.3f.", prtl_cor)

[1] "The partial correlation is 0.629."

The correlation coeifficient increases from -0.118 to 0.629. In my opinion, it is resonable to expect that the longer sepal length the Iris flower has, the longer the sepal width it has. Hence, the result looks much acceptable after controlling the effect on petal length and petal width.

## Creating Custom Function for K Nearest Neighbours Classifier

The `kNN` function can be used to build the classifier and make prediction.

The `kNN` function takes the following argument:
* **test** - testing vector
* **Train** - matrix or data frame of trainning data
* **Class** - factor/category for each row of trainning data
* **k** - number of nearest neighbours the model will consider

In [9]:
# Create kNN function
kNN <- function(test, Train, Class, k){
    test <- as.matrix(test); Train <- as.matrix(Train); Class <- as.matrix(Class)
    distance <- NULL
    for(i in 1:nrow(Train)){
        distance[i] <- dist(rbind(test, Train[i,]))
    }
    temp <- cbind(distance, Class)
    ClassSort <- temp[order(distance),]
    class <- names(which.max(table(ClassSort[1:k,2])))
    return(class)
}

## Model Trainning

Now I'll normalise the dataset before trainning the model, and then I'll shuffle and split them into trainning and testing dataset.

In [10]:
# Normalise dataset
iris2 <- as.data.frame(lapply(iris[,1:4], scale))
iris2 <- cbind(iris2, iris$Species)

# Shuffle dataset
rand <- sample(nrow(iris2))
iris3 <- iris2[rand,]

# Split dataset
split_pt <- round(nrow(iris3)*0.25,0)
Test <- iris3[1:split_pt,1:4]
Train <- iris3[(split_pt+1):nrow(iris3),1:4]
Class <- iris3[(split_pt+1):nrow(iris3),5]

Now use the custom function `kNN` to build the model and make prediction on the Iris flower dataset.

In [11]:
# Build model and make prediction
result <- NA
for(i in 1:nrow(Test)){
    result[i] <- kNN(Test[i,], Train, Class, k=21)
}

The `result` variable saved the predicted Iris species of testing dataset.

## Evaluating Model Performance

Now I'll evaluate the model performance using contingency table.

In [12]:
# Evaluate performance
real <- iris3[1:split_pt,5]
CrossTable(result, real, prop.chisq=F, prop.t=F, dnn=c("predict","actual"))


 
   Cell Contents
|-------------------------|
|                       N |
|           N / Row Total |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  38 

 
             | actual 
     predict |     setosa | versicolor |  virginica |  Row Total | 
-------------|------------|------------|------------|------------|
      setosa |         10 |          0 |          0 |         10 | 
             |      1.000 |      0.000 |      0.000 |      0.263 | 
             |      1.000 |      0.000 |      0.000 |            | 
-------------|------------|------------|------------|------------|
  versicolor |          0 |         15 |          2 |         17 | 
             |      0.000 |      0.882 |      0.118 |      0.447 | 
             |      0.000 |      0.938 |      0.167 |            | 
-------------|------------|------------|------------|------------|
   virginica |          0 |          1 |         10 |         11 | 
             |      0.000 |     

There are 4 out of 38 Iris species cannot be classifed to the correct category. However, in the absence of sufficient samples, the model can still correctly classify the Iris flower species with about 90% accuracy. In my opinion, the model has performed very well.

To enhance the accuracy of the classifier, we can increase the sample size of trainning dataset or adjust the value of k used in `kNN` function.